main: com.massivecraft.factions.Factions
name: Factions
version: 2.1.0
website: http://massivecraft.com/factions
authors: [Cayorion, Brettflan]
description: 搂eFactions allows the players to team up and claim land as their own and start wars with other factions. This way we hope to inspire politics, intrigue, and team spirit. 搂aCayorion 搂efrom the minecraft server 搂aMassiveCraft 搂eis the lead Factions programmer. Feel free to visit us at 搂bhttp://massivecraft.com
depend: [mcore]
softdepend: [PermissionsEx, Permissions, Essentials, EssentialsChat, HeroChat, iChat, LocalAreaChat, LWC, nChat, ChatManager, AuthMe, Vault, Spout, WorldEdit, WorldGuard, AuthDB, CaptureThePoints, CombatTag]
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  factions.access: {description: manage access, with the proper fperm, default: false}
  factions.access.faction: {description: grant faction access, with the proper fperm, default: false}
  factions.access.player: {description: grant player access, with the proper fperm, default: false}
  factions.access.view: {description: view access, default: false}
  factions.admin: {description: 是否允许管理员模式, default: false}
  factions.autoclaim: {description: 当你在走路的时候自动圈地占领, default: false}
  factions.claim: {description: 在你站的地方圈地, default: false}
  factions.claim.radius: {description: 以范围多少来圈地, default: false}
  factions.create: {description: 创建一个新的公会, default: false}
  factions.demote: {description: 贬职你公会里的成员, default: false}
  factions.description: {description: 变更公会口号, default: false}
  factions.disband: {description: 解散工会, default: false}
  factions.faction: {description: 显示所属公会信息, default: false}
  factions.flag: {description: 管理公会flags, default: false}
  factions.flag.set: {description: 设置公会flags, default: false}
  factions.home: {description: 返回公会传送点, default: false}
  factions.invite: {description: 邀请某玩家加入公会, default: false}
  factions.join: {description: 加入一个公会, default: false}
  factions.join.any: {description: 加入一个封闭的公会, default: false}
  factions.join.others: {description: have another player join faction, default: false}
  factions.kick: {description: 从公会中踢出某玩家, default: false}
  factions.leader: {description: 设置公会会长, default: false}
  factions.leader.any: {description: 设置别的公会会长, default: false}
  factions.leave: {description: 离开你在的公会, default: false}
  factions.list: {description: 列出所有公会, default: false}
  factions.map: {description: 显示领地地图, default: false}
  factions.money: {description: 管理公会资金, default: false}
  factions.money.balance: {description: 显示公会资金, default: false}
  factions.money.balance.any: {description: 显示其他公会的公会资金, default: false}
  factions.money.deposit: {description: 向公会银行存款, default: false}
  factions.money.f2f: {description: 划拨资金 公会 --> 公会, default: false}
  factions.money.f2p: {description: 划拨资金 公会 --> 玩家, default: false}
  factions.money.p2f: {description: 划拨资金 玩家 --> 公会, default: false}
  factions.money.withdraw: {description: 从公会银行取款, default: false}
  factions.officer: {description: 任命公会助理, default: false}
  factions.officer.any: {description: 设置其他公会的公会助理, default: false}
  factions.open: {description: 设置是否需要邀请加入公会, default: false}
  factions.perm: {description: 变更公会权限, default: false}
  factions.player: {description: 显示个人信息或者其他玩家的信息}
  factions.powerboost: {description: 设置能量提升, default: false}
  factions.promote: {description: 提升公会中的会员职务, default: false}
  factions.relation: {description: 设置与别的公会的关系, default: false}
  factions.seechunk: {description: see the chunk you stand in, default: false}
  factions.sethome: {description: 设置公会回城点, default: false}
  factions.name: {description: 设置公会名称, default: false}
  factions.title: {description: 设置玩家头衔, default: false}
  factions.title.color: {description: 设置玩家头衔的颜色, default: false}
  factions.unclaim: {description: 释放你脚下的领土, default: false}
  factions.unclaimall: {description: 释放所有领土, default: false}
  factions.version: {description: 查看插件版本, default: false}
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  factions.*:
    children:
      factions.access: true
      factions.access.faction: true
      factions.access.player: true
      factions.access.view: true
      factions.admin: true
      factions.autoclaim: true
      factions.claim: true
      factions.claim.radius: true
      factions.create: true
      factions.demote: true
      factions.description: true
      factions.disband: true
      factions.faction: true
      factions.flag: true
      factions.flag.set: true
      factions.home: true
      factions.invite: true
      factions.join: true
      factions.join.any: true
      factions.join.others: true
      factions.kick: true
      factions.leader: true
      factions.leader.any: true
      factions.leave: true
      factions.list: true
      factions.map: true
      factions.money: true
      factions.money.balance: true
      factions.money.balance.any: true
      factions.money.deposit: true
      factions.money.f2f: true
      factions.money.f2p: true
      factions.money.p2f: true
      factions.money.withdraw: true
      factions.officer: true
      factions.officer.any: true
      factions.open: true
      factions.perm: true
      factions.player: true
      factions.powerboost: true
      factions.promote: true
      factions.relation: true
      factions.seechunk: true
      factions.sethome: true
      factions.name: true
      factions.title: true
      factions.title.color: true
      factions.unclaim: true
      factions.unclaimall: true
      factions.version: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  factions.kit.op:
    default: op
    children:
      factions.*: true
  factions.kit.rank3:
    default: false
    children:
      factions.kit.rank2: true
  factions.kit.rank2:
    default: false
    children:
      factions.kit.rank1: true
      factions.flag.set: true
      factions.powerboost: true
      factions.join.any: true
      factions.join.others: true
      factions.leader.any: true
      factions.officer.any: true
      factions.access.any: true
  factions.kit.rank1:
    default: false
    children:
      factions.kit.rank0: true
      factions.admin: true
  factions.kit.rank0:
    default: false
    children:
      factions.access: true
      factions.access.faction: true
      factions.access.player: true
      factions.access.view: true
      factions.autoclaim: true
      factions.claim: true
      factions.claim.radius: true
      factions.create: true
      factions.demote: true
      factions.description: true
      factions.disband: true
      factions.faction: true
      factions.flag: true
      factions.home: true
      factions.invite: true
      factions.join: true
      factions.kick: true
      factions.leader: true
      factions.leave: true
      factions.list: true
      factions.map: true
      factions.money: true
      factions.money.balance: true
      factions.money.balance.any: true
      factions.money.deposit: true
      factions.money.f2f: true
      factions.money.f2p: true
      factions.money.p2f: true
      factions.money.withdraw: true
      factions.officer: true
      factions.open: true
      factions.perm: true
      factions.player: true
      factions.promote: true
      factions.relation: true
      factions.seechunk: true
      factions.sethome: true
      factions.name: true
      factions.title: true
      factions.title.color: true
      factions.unclaim: true
      factions.unclaimall: true
      factions.version: true
  factions.kit.default:
    default: true
    children:
      factions.kit.rank0: true